name: WakaTime Readme Stats - CodeLine

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with CodeLine
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: 'CodeLine'
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: 'Updated WakaTime Metrics'
          COMMIT_USERNAME: 'Dercraker'
          COMMIT_EMAIL: 'antoine.capitain@gmail.com'
          SHOW_LINES_OF_CODE: true
