name: WakaTime Readme Stats - GithubStats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  update-readme:
    name: Update Readme with GithubStats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: 'GithubStats'
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: 'Updated WakaTime Metrics'
          COMMIT_USERNAME: 'Dercraker'
          COMMIT_EMAIL: 'antoine.capitain@gmail.com'
          SHOW_SHORT_INFO: true
