name: WakaTime Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Wakatime Stats on top 5 language on last 30 days
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494
        with:
          API_BASE_URL: ${{ secrets.WAKAPI_BASE_URL }}
          WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: '⬜🟨🟩'
          TIME_RANGE: last_30_days
          SHOW_TIME: true
