name: WakaTime Readme Stats - UpdateTime

on:
  schedule:
    - cron: '25 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with UpdateTime
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: 'UpdateTime'
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: 'Updated WakaTime Metrics'
          COMMIT_USERNAME: 'Dercraker'
          COMMIT_EMAIL: 'antoine.capitain@gmail.com'
          SHOW_UPDATED_DATE: true

          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          SHOW_TOTAL_CODE_TIME: false
